// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gas_gc_restrictParams
arma::vec gas_gc_restrictParams(arma::vec vParams);
RcppExport SEXP DCS_gas_gc_restrictParams(SEXP vParamsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::vec >::type vParams(vParamsSEXP );
        arma::vec __result = gas_gc_restrictParams(vParams);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gas_gc_llCpp
double gas_gc_llCpp(arma::vec vParams, int iT, arma::mat mData);
RcppExport SEXP DCS_gas_gc_llCpp(SEXP vParamsSEXP, SEXP iTSEXP, SEXP mDataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::vec >::type vParams(vParamsSEXP );
        Rcpp::traits::input_parameter< int >::type iT(iTSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type mData(mDataSEXP );
        double __result = gas_gc_llCpp(vParams, iT, mData);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
