// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fnRestrictedParams
arma::vec fnRestrictedParams(arma::vec vParams);
RcppExport SEXP DCS_fnRestrictedParams(SEXP vParamsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::vec >::type vParams(vParamsSEXP );
        arma::vec __result = fnRestrictedParams(vParams);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fnGASGaussianCopulaLikelihoodCpp
double fnGASGaussianCopulaLikelihoodCpp(arma::vec vParams, int iT, arma::mat mData);
RcppExport SEXP DCS_fnGASGaussianCopulaLikelihoodCpp(SEXP vParamsSEXP, SEXP iTSEXP, SEXP mDataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::vec >::type vParams(vParamsSEXP );
        Rcpp::traits::input_parameter< int >::type iT(iTSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type mData(mDataSEXP );
        double __result = fnGASGaussianCopulaLikelihoodCpp(vParams, iT, mData);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
