# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnRestrictedParams <- function(vParams) {
    .Call('DCS_fnRestrictedParams', PACKAGE = 'DCS', vParams)
}

fnGASGaussianCopulaLikelihoodCpp <- function(vParams, iT, mData) {
    .Call('DCS_fnGASGaussianCopulaLikelihoodCpp', PACKAGE = 'DCS', vParams, iT, mData)
}

