# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gas_gc_restrictParams <- function(vParams) {
    .Call('DCS_gas_gc_restrictParams', PACKAGE = 'DCS', vParams)
}

#' Log-likelihood of the GAS Gaussian copula model
#' 
#' Returns the scaled negative log-likelihood of the GAS Gaussian copula model for a given
#' set of parameters and data matrix
#' @export
gas_gc_llCpp <- function(vParams, iT, mData) {
    .Call('DCS_gas_gc_llCpp', PACKAGE = 'DCS', vParams, iT, mData)
}

